#pragma once

#define VERSION_FULL 4.9.9.100
#define VERSION_MAJOR 4
#define VERSION_MINOR 9
#define VERSION_REVISION 9
#define VERSION_BUILD 100

#define VERSION_STRING_FILE "4.9.9.100"
#define VERSION_STRING_PRODUCT "4.9.9"
