/*
 * MariusFX preview .exe — Win32 + DirectX 11 + ImGui shell that hosts
 * the production ui.cpp source against a self-contained mock runtime.
 *
 * Iterate on the UI without restarting FiveM:
 *
 *     scripts\build_preview.bat
 *     bin\preview\preview.exe
 *
 * Edit any file under mariusfx/ui/ then re-run the batch — full rebuild
 * is a few seconds.
 */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d11.h>
#include <tchar.h>

#include <imgui.h>
#include <imgui_impl_win32.h>
#include <imgui_impl_dx11.h>

#include "../ui.hpp"
#include "../theme.hpp"
#include "preview_runtime.hpp"

#include <filesystem>
#include <fstream>

// Animation tick exposed by preview_runtime.cpp.
namespace mariusfx_preview { void tick_anim(float dt); }

// ── DX11 globals ───────────────────────────────────────────────────────────
static ID3D11Device           *g_device     = nullptr;
static ID3D11DeviceContext    *g_context    = nullptr;
static IDXGISwapChain         *g_swapchain  = nullptr;
static ID3D11RenderTargetView *g_main_rtv   = nullptr;
static UINT                    g_resize_w   = 0, g_resize_h = 0;

static bool create_d3d_device(HWND hwnd);
static void cleanup_d3d_device();
static void create_render_target();
static void cleanup_render_target();
static LRESULT WINAPI wnd_proc(HWND, UINT, WPARAM, LPARAM);

extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND, UINT, WPARAM, LPARAM);

// ── Main loop ──────────────────────────────────────────────────────────────
int WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int)
{
    ImGui_ImplWin32_EnableDpiAwareness();
    const float dpi = ImGui_ImplWin32_GetDpiScaleForMonitor(::MonitorFromPoint(POINT{0, 0}, MONITOR_DEFAULTTOPRIMARY));

    WNDCLASSEXW wc = { sizeof(wc), CS_CLASSDC, wnd_proc, 0L, 0L,
                       GetModuleHandle(nullptr), nullptr, nullptr, nullptr,
                       nullptr, L"MariusFXPreview", nullptr };
    ::RegisterClassExW(&wc);

    HWND hwnd = ::CreateWindowW(
        wc.lpszClassName, L"MariusFX preview",
        WS_OVERLAPPEDWINDOW,
        100, 100,
        (int)(1280 * dpi), (int)(800 * dpi),
        nullptr, nullptr, wc.hInstance, nullptr);

    if (!create_d3d_device(hwnd))
    {
        cleanup_d3d_device();
        ::UnregisterClassW(wc.lpszClassName, wc.hInstance);
        return 1;
    }
    ::ShowWindow(hwnd, SW_SHOWDEFAULT);
    ::UpdateWindow(hwnd);

    IMGUI_CHECKVERSION();
    ImGui::CreateContext();
    ImGuiIO &io = ImGui::GetIO();
    io.IniFilename = nullptr;
    io.LogFilename = nullptr;
    io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;

    ImGui_ImplWin32_Init(hwnd);
    ImGui_ImplDX11_Init(g_device, g_context);

    // Apply MariusFX theme (same code as in the DLL).
    mariusfx::ui::init();

    // Persistent mock runtime — keeps technique enabled state, uniform
    // values etc. across frames so widget changes feel real.
    reshade::runtime mock_rt;

    // ── Seed a real mock_presets/ folder next to the .exe ─────────────
    // The new preset picker uses std::filesystem, so we point the mock
    // at an actual directory with a handful of `.ini` files so loading /
    // creating / renaming / deleting all work end-to-end in the preview.
    {
        namespace fs = std::filesystem;
        wchar_t exe_path[MAX_PATH] = {};
        ::GetModuleFileNameW(nullptr, exe_path, MAX_PATH);
        fs::path exe_dir = fs::path(exe_path).parent_path();
        fs::path presets_dir = exe_dir / L"mock_presets";
        std::error_code ec;
        fs::create_directories(presets_dir, ec);
        const char *seeds[] = {
            "MariusFX_Quality.ini",
            "MariusFX_Performance.ini",
            "MariusFX_Cinematic.ini",
            "Night_Drive.ini",
            "Sunset_Warm.ini",
        };
        for (const char *n : seeds)
        {
            fs::path p = presets_dir / n;
            if (!fs::exists(p, ec))
            {
                std::ofstream f(p);
                f << "; MariusFX preset placeholder — generated by preview.exe\n";
            }
        }
        // Point the mock runtime at the first preset.
        fs::path initial = presets_dir / seeds[0];
        mock_rt.set_current_preset_path(initial.string().c_str());
    }

    bool done = false;
    while (!done)
    {
        MSG msg;
        while (::PeekMessage(&msg, nullptr, 0U, 0U, PM_REMOVE))
        {
            ::TranslateMessage(&msg);
            ::DispatchMessage(&msg);
            if (msg.message == WM_QUIT) done = true;
        }
        if (done) break;

        if (g_resize_w != 0 && g_resize_h != 0)
        {
            cleanup_render_target();
            g_swapchain->ResizeBuffers(0, g_resize_w, g_resize_h, DXGI_FORMAT_UNKNOWN, 0);
            g_resize_w = g_resize_h = 0;
            create_render_target();
        }

        ImGui_ImplDX11_NewFrame();
        ImGui_ImplWin32_NewFrame();
        ImGui::NewFrame();

        mariusfx_preview::tick_anim(io.DeltaTime);

        // Docked overlay — pos/size/flags driven by the UI module so the
        // dock-toggle and resize handle work the same in preview as in
        // production.
        const ImGuiViewport *vp = ImGui::GetMainViewport();
        ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding,   0.0f);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding,    ImVec2(0, 0));
        const ImGuiWindowFlags mfx_flags = mariusfx::ui::configure_next_window(
            vp->WorkPos, vp->WorkSize);
        ImGui::Begin("##MariusFXPreviewRoot", nullptr, mfx_flags);

        mariusfx::ui::render(&mock_rt);

        ImGui::End();
        ImGui::PopStyleVar(3);

        ImGui::Render();
        const float clear[4] = { 0.04f, 0.06f, 0.10f, 1.0f };
        g_context->OMSetRenderTargets(1, &g_main_rtv, nullptr);
        g_context->ClearRenderTargetView(g_main_rtv, clear);
        ImGui_ImplDX11_RenderDrawData(ImGui::GetDrawData());

        g_swapchain->Present(1, 0);
    }

    ImGui_ImplDX11_Shutdown();
    ImGui_ImplWin32_Shutdown();
    ImGui::DestroyContext();
    cleanup_d3d_device();
    ::DestroyWindow(hwnd);
    ::UnregisterClassW(wc.lpszClassName, wc.hInstance);
    return 0;
}

// ── DX11 helpers (cribbed from imgui_examples/example_win32_directx11) ─────
static bool create_d3d_device(HWND hwnd)
{
    DXGI_SWAP_CHAIN_DESC sd = {};
    sd.BufferCount = 2;
    sd.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    sd.BufferDesc.RefreshRate.Numerator = 60;
    sd.BufferDesc.RefreshRate.Denominator = 1;
    sd.Flags = DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH;
    sd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
    sd.OutputWindow = hwnd;
    sd.SampleDesc.Count = 1;
    sd.Windowed = TRUE;
    sd.SwapEffect = DXGI_SWAP_EFFECT_DISCARD;

    const D3D_FEATURE_LEVEL fls[2] = { D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_0 };
    D3D_FEATURE_LEVEL fl;
    HRESULT hr = D3D11CreateDeviceAndSwapChain(
        nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, 0,
        fls, 2, D3D11_SDK_VERSION,
        &sd, &g_swapchain, &g_device, &fl, &g_context);
    if (hr == DXGI_ERROR_UNSUPPORTED)
        hr = D3D11CreateDeviceAndSwapChain(
            nullptr, D3D_DRIVER_TYPE_WARP, nullptr, 0,
            fls, 2, D3D11_SDK_VERSION,
            &sd, &g_swapchain, &g_device, &fl, &g_context);
    if (FAILED(hr)) return false;

    create_render_target();
    return true;
}

static void cleanup_d3d_device()
{
    cleanup_render_target();
    if (g_swapchain) { g_swapchain->Release(); g_swapchain = nullptr; }
    if (g_context)   { g_context->Release();   g_context   = nullptr; }
    if (g_device)    { g_device->Release();    g_device    = nullptr; }
}

static void create_render_target()
{
    ID3D11Texture2D *bb = nullptr;
    g_swapchain->GetBuffer(0, IID_PPV_ARGS(&bb));
    if (bb)
    {
        g_device->CreateRenderTargetView(bb, nullptr, &g_main_rtv);
        bb->Release();
    }
}

static void cleanup_render_target()
{
    if (g_main_rtv) { g_main_rtv->Release(); g_main_rtv = nullptr; }
}

static LRESULT WINAPI wnd_proc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp)
{
    if (ImGui_ImplWin32_WndProcHandler(hwnd, msg, wp, lp)) return true;

    switch (msg)
    {
    case WM_SIZE:
        if (wp != SIZE_MINIMIZED) { g_resize_w = (UINT)LOWORD(lp); g_resize_h = (UINT)HIWORD(lp); }
        return 0;
    case WM_SYSCOMMAND:
        if ((wp & 0xfff0) == SC_KEYMENU) return 0;
        break;
    case WM_DESTROY:
        ::PostQuitMessage(0);
        return 0;
    }
    return ::DefWindowProcW(hwnd, msg, wp, lp);
}
